production:
  main_file_url: https://docs.google.com/spreadsheets/d/1O8VUGZGM8TmqZPFXsLCHSmg0gKjd1exGp9La_5olnxQ
  mirror_file_url: https://docs.google.com/spreadsheets/d/1PblLcW6NJZ8qke7-aBlnuoFJDi8ZTc6sjbH7quBAMMo
  view_sheet_name: Cases
  preferred_date_format: '%d-%b-%Y'
testing:
  main_file_url: https://docs.google.com/spreadsheets/d/1O8VUGZGM8TmqZPFXsLCHSmg0gKjd1exGp9La_5olnxQ
  mirror_file_url: https://docs.google.com/spreadsheets/d/1PblLcW6NJZ8qke7-aBlnuoFJDi8ZTc6sjbH7quBAMMo
  view_sheet_name: Cases
  preferred_date_format: '%d-%b-%Y'
